### ISSUE TITLE
Templates contain duplicate/redundant institution and scanner information

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-methods#3]
Looking at the example in `pybids-reports`, there is redundant information about the institution and scanner.

> The data acquisition was performed in the , , .
> MRI data were acquired using a UNKNOWN Tesla using a  system from ,
> with serial number . The software version was .One run of   UNKNOwN SEQUENCE UNKNOwN SEQUENCE VARIANT single-echo 
> structural MRI data were collected (repetition time, TR= 2500.0 ms; flip angle, FA= 8°; echo time, TE= 2.9 ms; 
> field of view FOV= 256x256 mm; matrix size= 256x256; voxel size= 1x1x1 mm; UNKNOWN slices).
> 
> 
> The data acquisition was performed in the , , .
> MRI data were acquired using a UNKNOWN Tesla using a  system from ,
> with serial number . The software version was .One run of   UNKNOwN SEQUENCE UNKNOwN SEQUENCE VARIANT single-echo 
> structural MRI data were collected (repetition time, TR= 2500.0 ms; flip angle, FA= 8°; echo time, TE= 2.9 ms; 
> field of view FOV= 256x256 mm; matrix size= 256x256; voxel size= 1x1x1 mm; UNKNOWN slices).
> 
> 
> The data acquisition was performed in the , , .
> MRI data were acquired using a UNKNOWN Tesla using a  system from ,
> with serial number . The software version was .One run of  UNKNOwN SEQUENCE UNKNOwN SEQUENCE VARIANT 
> diffusion-weighted-imaging () data were collected (68 slices; repetition time, TR= 8400.0 ms; flip angle, FA= 90°; 
> echo time, TE= 90 ms; field of view FOV= 128x128 mm; matrix size= 64x64; voxel size= 2x2x2 mm; b-values of 0 and 
> 1000 acquired; 64 diffusion directions;  ).

The relevant portion is:

> The data acquisition was performed in the , , .
> MRI data were acquired using a UNKNOWN Tesla using a  system from ,
> with serial number .

**Comment by Remi-Gau** [comment]
yeah that's because the template for each MRI datatype will include the partials for institutions and scanner info.

https://github.com/bids-standard/bids-methods/blob/bdbd36a13a4364892183885dd82ab4cab046f71a/templates/anat.mustache#L1

https://github.com/bids-standard/bids-methods/blob/bdbd36a13a4364892183885dd82ab4cab046f71a/templates/dwi.mustache#L1

do you think that we should not include those in the templates and let the tools that use the templates decide if they want to include them for each MRI sequence or not?

**Comment by tsalo** [comment]
That's what I was thinking. Optimally, pybids-reports would put them at the beginning of the session-level description, just once.

**Comment by Remi-Gau** [comment]
OK makes sense to me to let the tools handle how they want to arrange those template blocks.

**Comment by Remi-Gau** [comment]
will refactor the templates.
