### ISSUE TITLE
Sentences with missing information are retained in the rendered text

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-methods#4]
In the pre-template version of BIDSReport, optional or recommended information that was missing was excluded from the rendered text. For example, when it comes to the MR scanner information, some info was required (or at least needed a stand-in value of "UNKNOWN"), while other info would just be dropped, but the current version has something like the following:

> MRI data were acquired using a UNKNOWN Tesla using a  system from , with serial number .

Instead, I think something like the following would be better:

> MRI data were acquired using a UNKNOWN Tesla scanner.

**Comment by Remi-Gau** [comment]
Yeah so for pybids-report there is a "keep" on main branch of chevron that would at least leave the name of the missing parameters rather than those annoying blanks.

But the package has not been updated in a long while... 😒 

https://github.com/noahmorrison/chevron/issues/114

**Comment by Remi-Gau** [comment]
Ideally I would prefer to have 

`MRI data were acquired using a UNKNOWN Tesla using a system from {{ bar }}, with serial number {{ foo }} .`

But I think this is something that should be handled by the pybids-reports

**Comment by tsalo** [comment]
That's reasonable. Can bids-methods handle conditional logic, or does that need to happen on pybids-reports' side?

**Comment by Remi-Gau** [comment]
yes the mustache templating language can handle some conditional logic, by using sections: https://mustache.github.io/mustache.5.html

See the mustache spec: https://github.com/mustache/spec/blob/master/specs/sections.yml

Let me create a MWE.

**Comment by Remi-Gau** [comment]
You can open and close "sections" with `{{#bla}}` and close them with `{{/bla}}`.

```python
import chevron

template = """Data was acquired on a {{model_name}} system
{{#manufacturer}}from {{manufacturer}}, {{/manufacturer}}
{{#DeviceSerialNumber}}with serial number {{DeviceSerialNumber}}{{/DeviceSerialNumber}}."""

data =  {'model_name': 'UNKNWON', "DeviceSerialNumber": 1234}

text = chevron.render(template, data)

print(text)
```

```bash
$ /home/remi/miniconda3/bin/python /home/remi/github/bids/pybids-reports/tmp.py

Data was acquired on a UNKNWON system

with serial number 1234.
```

Does that help?

**Comment by Remi-Gau** [comment]
We could add some conditional logic in the templates that way to avoid some of ugliest renders.

**Comment by Remi-Gau** [comment]
I will try to address #7  and then I can try to update pybids-report accordingly to take this into account
